---Optimization and Graphics
NDefines.NGame.DAYS_BEHIND_PAUSE = 90
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 45
NDefines.NGui.AUTO_SELECT_EVENT_MONTHS = 6
NDefines.NEngine.EVENT_PROCESS_OFFSET = 30

--Diplo 
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_LOSE = 0				
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_GAIN = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_WARSCORE = 0
NDefines.NDiplomacy.DEFENDER_OF_FAITH_TRUST_LOSS = 0
NDefines.NDiplomacy.MAX_ASKED_TRADE_POWER = 100
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 6
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MINIMUM_TRADE_POWER_TO_PREVENT_PRIVATEER = 0.1
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0
NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MIN_MONTHS = 6
NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MONTHS = -1

--Country
NDefines.NCountry.ABDICATE_LEGITIMACY_THRESHOLD = 0
NDefines.NCountry.ABDICATE_AGE_THRESHOLD = 30
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 10
NDefines.NCountry.ABDICATE_LEGITIMACY_HIT = 0
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.NEW_HEIR_LEGITIMACY_HIT = 0
NDefines.NCountry.NEW_HEIR_LEGITIMACY_THRESHOLD = 0
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 30.5
NDefines.NCountry.MONARCH_DEATH_LEADER_STABILITY_PENALTY = 0
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_2 = 1			
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_3 = 25
NDefines.NCountry.NAT_FOCUS_YEARS = 5
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.PS_ASSAULT = 0
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 15
NDefines.NCountry.PS_MOVE_TRADE_PORT = 50
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 40

NDefines.NCountry.PS_REMOVE_ACCEPTED_CULTURE = 0
NDefines.NCountry.STRENGTHEN_GOVERNMENT_LEGITIMACY = 25
NDefines.NCountry.PROVOKE_REVOLT_MIN_PROGRESS = 30.0
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.BREAK_VASSAL_PRESTIGE_PENALTY = 0
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_TECHNOLOGY = 25
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0

--Economy
NDefines.NEconomy.DECREASE_AUTONOMY_MIN = 0
NDefines.NEconomy.EDICTS_DURATION_MONTHS = 1
NDefines.NEconomy.PIRATES_TRADE_POWER_FACTOR = 0.1
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 5 -- Non cambiato dal vanilla, potrei cambiarlo in futuro ( divisore del TP, più aumenta questo valore, meno trade power viene trasferito da downstream )

--Military
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.7
NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0	-- Daje i cannoni sono di nuovo come nelle patch precedenti
NDefines.NMilitary.BACK_LINE_STRENGTH_DAMAGE_TAKEN_MODIFIER = 0.0
NDefines.NMilitary.CANNOT_RETREAT_DAYS = 1

--Religion 
NDefines.NReligion.MAX_CHURCH_POWER = 300
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 20
NDefines.NReligion.STARTING_HARMONY = 50.0
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 2.0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -5.0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.05
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = 0

--AI
NDefines.NAI.BUY_INDULGENCE_BASE_AI_DESIRE = -1
NDefines.NAI.BUY_INDULGENCE_RIVAL_AI_DESIRE = -1					
NDefines.NAI.BUY_INDULGENCE_EXCOM_AI_DESIRE = -1